### ISSUE TITLE
Is it possible to drag handles even without changing anything?

### ISSUE THREAD

**Issue by Luocheng-Zheng** [cmm-21/a4#1]
Hello!

I have just run fem-app.cpp, but I could not drag the handles. I wonder if it is possible to drag handles even without changing anything? My laptop is Macbook pro (Retina), so I am afraid that something went wrong.
<img width="718" alt="Screen Shot 2021-04-15 at 10 52 40 PM" src="https://user-images.githubusercontent.com/38021867/114936920-60d99d00-9e3d-11eb-8737-92c510353d03.png">

**Comment by liyuesolo** [comment]
Hi, no Mac available at hand, I'll get back to you tmr.

**Comment by vullnetu** [comment]
same problem here. I also get this unusual error message. Can I ignore this ?
 CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):The package name passed to `find_package_handle_standard_args` (JSON) does
not match the name of the calling package (Json).  This can lead to
problems in calling code that expects `find_package` result variables
(e.g., `_FOUND`) to follow a certain pattern.CMake (message)
FindJson.cmake(18, 1): In call to 'find_package_handle_standard_args' here
CMakeLists.txt(3, 1): In call to 'find_package' here 

I think it has something to do with the cursor because when I use the draw cursor option, it shows me a shifted position from its actual position.
Moreover I found some strange if statements in simulation.h:
		`if (energy.APPLY_GRAVITY = APPLY_GRAVITY) {`
			`energy.f_ext = f_ext;`
		`}`
		`if (energy.SOLVE_DYNAMICS = SOLVE_DYNAMICS) {`
			`energy.x_prev = (x_prev.size() != 0) ? x_prev : this->x;`
			`energy.v_prev = (v_prev.size() != 0) ? v_prev : this->v;`
			`energy.h = h;`
			`energy.M = M;`

shouldn't it be "==" instead of "="

**Comment by Glanfaloth** [comment]
Same issue here. Any solution?

**Comment by liyuesolo** [comment]
You can ignore the warning.

**Comment by liyuesolo** [comment]
set bool I_AM_HAVING_SCREEN_ISSUES = true in fem-app.cpp; and it will work on MacOS

**Comment by Luocheng-Zheng** [comment]
Solved, thank you very much!

**Comment by Luocheng-Zheng** [comment]
> set bool I_AM_HAVING_SCREEN_ISSUES = true in fem-app.cpp; and it will work on MacOS
